# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo apt-get update -qq
- sudo apt-get install gdal-bin
- sudo apt-get --purge remove libcurl4-openssl-dev libgdal1 postgresql-*
- sudo apt-get install aptitude 
- sudo aptitude install libproj-dev gdal-bin libgdal1=1.11.1 libgdal-dev -y
- sudo apt-get install libcurl4-openssl-dev
- Rscript -e 'install.packages("SSOAP", repos="http://www.omegahat.org/R", type="source")'
- Rscript -e 'install.packages("XMLSchema", repos="http://www.omegahat.org/R", type="source")'

r_binary_packages:
- rgdal
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- bocinsky/FedData

# after_success:

notifications:
email:
on_success: change
on_failure: change
